### ISSUE TITLE
NPE in concierge (likely with bad/stale registration, but.. )

### ISSUE THREAD

**Issue by ebullient** [gameontext/gameon-room#31]
Caused by: java.lang.NullPointerException
	at net.wasdev.gameon.concierge.ConciergeEndpoint.exitRoom(ConciergeEndpoint.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.ibm.ws.jaxrs20.cdi.component.JaxRsFactoryBeanCDICustomizer.serviceInvoke(JaxRsFactoryBeanCDICustomizer.java:211)
	... 1 more

	public Response exitRoom(@PathParam("roomId") String roomId, @PathParam("exitName") String exitName) {
		RoomToEndpoints ec = c.exitRoom(roomId, exitName);

		if ( ec.getEndpoints().isEmpty() )
			return Response.status(404).build();

		RoomToEndpointsWrapper ew = new RoomToEndpointsWrapper();

**Comment by ebullient** [comment]
No longer applies.
